# -*- coding: utf-8 -*-
"""TMKOC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yz_I0n5ihZ5CFxXBzRgoPK3yRrvIk0oc
"""

import pandas as pd

data = pd.read_csv("TMKOC_EPISODES_41.csv")

def extract_runtime(rn):
    return rn.replace("FULL_HD1", "")

data['Episode_runtime'] = data['Episode_runtime'].apply(extract_runtime)

def extract_episode_number(s):
  parts = s.split(".")
  return int(parts[0])

def extract_episode_title(s):
  parts = s.split(".")
  return parts[1]

data.iloc[0:100, data.columns.get_loc('Episode_title')] = data.iloc[0:100, data.columns.get_loc('Episode_title')].apply(extract_episode_title)

data['episode_number'] = data['episode_number'].apply(extract_episode_number)

data['Episode_title'] = data['Episode_title'].apply(extract_episode_title)

pd.set_option('display.max_rows', None)
data

data.to_csv("TMKOC 4001_4100.csv")